# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_register.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 721, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.hex_tab = QtWidgets.QWidget()
        self.hex_tab.setObjectName("hex_tab")
        self.line = QtWidgets.QFrame(self.hex_tab)
        self.line.setGeometry(QtCore.QRect(10, 100, 721, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.hex_tab)
        self.line_2.setGeometry(QtCore.QRect(10, 230, 721, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(self.hex_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 461, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_75 = QtWidgets.QVBoxLayout()
        self.verticalLayout_75.setObjectName("verticalLayout_75")
        self.label_81 = QtWidgets.QLabel(self.layoutWidget)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_75.addWidget(self.label_81)
        self.check_32_15 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_15.setText("")
        self.check_32_15.setObjectName("check_32_15")
        self.verticalLayout_75.addWidget(self.check_32_15)
        self.horizontalLayout_4.addLayout(self.verticalLayout_75)
        self.verticalLayout_76 = QtWidgets.QVBoxLayout()
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.label_82 = QtWidgets.QLabel(self.layoutWidget)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_76.addWidget(self.label_82)
        self.check_32_14 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_14.setText("")
        self.check_32_14.setObjectName("check_32_14")
        self.verticalLayout_76.addWidget(self.check_32_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_76)
        self.verticalLayout_77 = QtWidgets.QVBoxLayout()
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.label_83 = QtWidgets.QLabel(self.layoutWidget)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_77.addWidget(self.label_83)
        self.check_32_13 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_13.setText("")
        self.check_32_13.setObjectName("check_32_13")
        self.verticalLayout_77.addWidget(self.check_32_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_77)
        self.verticalLayout_78 = QtWidgets.QVBoxLayout()
        self.verticalLayout_78.setObjectName("verticalLayout_78")
        self.label_84 = QtWidgets.QLabel(self.layoutWidget)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_78.addWidget(self.label_84)
        self.check_32_12 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_12.setText("")
        self.check_32_12.setObjectName("check_32_12")
        self.verticalLayout_78.addWidget(self.check_32_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_78)
        self.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.label_85 = QtWidgets.QLabel(self.layoutWidget)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_79.addWidget(self.label_85)
        self.check_32_11 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_11.setText("")
        self.check_32_11.setObjectName("check_32_11")
        self.verticalLayout_79.addWidget(self.check_32_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_79)
        self.verticalLayout_80 = QtWidgets.QVBoxLayout()
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.label_86 = QtWidgets.QLabel(self.layoutWidget)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_80.addWidget(self.label_86)
        self.check_32_10 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_10.setText("")
        self.check_32_10.setObjectName("check_32_10")
        self.verticalLayout_80.addWidget(self.check_32_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_80)
        self.verticalLayout_81 = QtWidgets.QVBoxLayout()
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.label_87 = QtWidgets.QLabel(self.layoutWidget)
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_81.addWidget(self.label_87)
        self.check_32_9 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_9.setText("")
        self.check_32_9.setObjectName("check_32_9")
        self.verticalLayout_81.addWidget(self.check_32_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_81)
        self.verticalLayout_82 = QtWidgets.QVBoxLayout()
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.label_88 = QtWidgets.QLabel(self.layoutWidget)
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_82.addWidget(self.label_88)
        self.check_32_8 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_8.setText("")
        self.check_32_8.setObjectName("check_32_8")
        self.verticalLayout_82.addWidget(self.check_32_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_82)
        self.verticalLayout_83 = QtWidgets.QVBoxLayout()
        self.verticalLayout_83.setObjectName("verticalLayout_83")
        self.label_89 = QtWidgets.QLabel(self.layoutWidget)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_83.addWidget(self.label_89)
        self.check_32_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_7.setText("")
        self.check_32_7.setObjectName("check_32_7")
        self.verticalLayout_83.addWidget(self.check_32_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_83)
        self.verticalLayout_84 = QtWidgets.QVBoxLayout()
        self.verticalLayout_84.setObjectName("verticalLayout_84")
        self.label_90 = QtWidgets.QLabel(self.layoutWidget)
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_84.addWidget(self.label_90)
        self.check_32_6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_6.setText("")
        self.check_32_6.setObjectName("check_32_6")
        self.verticalLayout_84.addWidget(self.check_32_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_84)
        self.verticalLayout_85 = QtWidgets.QVBoxLayout()
        self.verticalLayout_85.setObjectName("verticalLayout_85")
        self.label_91 = QtWidgets.QLabel(self.layoutWidget)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_85.addWidget(self.label_91)
        self.check_32_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_5.setText("")
        self.check_32_5.setObjectName("check_32_5")
        self.verticalLayout_85.addWidget(self.check_32_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_85)
        self.verticalLayout_86 = QtWidgets.QVBoxLayout()
        self.verticalLayout_86.setObjectName("verticalLayout_86")
        self.label_92 = QtWidgets.QLabel(self.layoutWidget)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_86.addWidget(self.label_92)
        self.check_32_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_4.setText("")
        self.check_32_4.setObjectName("check_32_4")
        self.verticalLayout_86.addWidget(self.check_32_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_86)
        self.verticalLayout_87 = QtWidgets.QVBoxLayout()
        self.verticalLayout_87.setObjectName("verticalLayout_87")
        self.label_93 = QtWidgets.QLabel(self.layoutWidget)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_87.addWidget(self.label_93)
        self.check_32_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_3.setText("")
        self.check_32_3.setObjectName("check_32_3")
        self.verticalLayout_87.addWidget(self.check_32_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_87)
        self.verticalLayout_88 = QtWidgets.QVBoxLayout()
        self.verticalLayout_88.setObjectName("verticalLayout_88")
        self.label_94 = QtWidgets.QLabel(self.layoutWidget)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_88.addWidget(self.label_94)
        self.check_32_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_2.setText("")
        self.check_32_2.setObjectName("check_32_2")
        self.verticalLayout_88.addWidget(self.check_32_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_88)
        self.verticalLayout_89 = QtWidgets.QVBoxLayout()
        self.verticalLayout_89.setObjectName("verticalLayout_89")
        self.label_95 = QtWidgets.QLabel(self.layoutWidget)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_89.addWidget(self.label_95)
        self.check_32_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_1.setText("")
        self.check_32_1.setObjectName("check_32_1")
        self.verticalLayout_89.addWidget(self.check_32_1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_89)
        self.verticalLayout_90 = QtWidgets.QVBoxLayout()
        self.verticalLayout_90.setObjectName("verticalLayout_90")
        self.label_96 = QtWidgets.QLabel(self.layoutWidget)
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_90.addWidget(self.label_96)
        self.check_32_0 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_0.setText("")
        self.check_32_0.setObjectName("check_32_0")
        self.verticalLayout_90.addWidget(self.check_32_0)
        self.horizontalLayout_4.addLayout(self.verticalLayout_90)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_91 = QtWidgets.QVBoxLayout()
        self.verticalLayout_91.setObjectName("verticalLayout_91")
        self.label_97 = QtWidgets.QLabel(self.layoutWidget)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.verticalLayout_91.addWidget(self.label_97)
        self.check_32_31 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_31.setText("")
        self.check_32_31.setObjectName("check_32_31")
        self.verticalLayout_91.addWidget(self.check_32_31)
        self.horizontalLayout_5.addLayout(self.verticalLayout_91)
        self.verticalLayout_92 = QtWidgets.QVBoxLayout()
        self.verticalLayout_92.setObjectName("verticalLayout_92")
        self.label_98 = QtWidgets.QLabel(self.layoutWidget)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_92.addWidget(self.label_98)
        self.check_32_30 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_30.setText("")
        self.check_32_30.setObjectName("check_32_30")
        self.verticalLayout_92.addWidget(self.check_32_30)
        self.horizontalLayout_5.addLayout(self.verticalLayout_92)
        self.verticalLayout_93 = QtWidgets.QVBoxLayout()
        self.verticalLayout_93.setObjectName("verticalLayout_93")
        self.label_99 = QtWidgets.QLabel(self.layoutWidget)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_93.addWidget(self.label_99)
        self.check_32_29 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_29.setText("")
        self.check_32_29.setObjectName("check_32_29")
        self.verticalLayout_93.addWidget(self.check_32_29)
        self.horizontalLayout_5.addLayout(self.verticalLayout_93)
        self.verticalLayout_94 = QtWidgets.QVBoxLayout()
        self.verticalLayout_94.setObjectName("verticalLayout_94")
        self.label_100 = QtWidgets.QLabel(self.layoutWidget)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_94.addWidget(self.label_100)
        self.check_32_28 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_28.setText("")
        self.check_32_28.setObjectName("check_32_28")
        self.verticalLayout_94.addWidget(self.check_32_28)
        self.horizontalLayout_5.addLayout(self.verticalLayout_94)
        self.verticalLayout_95 = QtWidgets.QVBoxLayout()
        self.verticalLayout_95.setObjectName("verticalLayout_95")
        self.label_101 = QtWidgets.QLabel(self.layoutWidget)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.verticalLayout_95.addWidget(self.label_101)
        self.check_32_27 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_27.setText("")
        self.check_32_27.setObjectName("check_32_27")
        self.verticalLayout_95.addWidget(self.check_32_27)
        self.horizontalLayout_5.addLayout(self.verticalLayout_95)
        self.verticalLayout_96 = QtWidgets.QVBoxLayout()
        self.verticalLayout_96.setObjectName("verticalLayout_96")
        self.label_102 = QtWidgets.QLabel(self.layoutWidget)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.verticalLayout_96.addWidget(self.label_102)
        self.check_32_26 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_26.setText("")
        self.check_32_26.setObjectName("check_32_26")
        self.verticalLayout_96.addWidget(self.check_32_26)
        self.horizontalLayout_5.addLayout(self.verticalLayout_96)
        self.verticalLayout_97 = QtWidgets.QVBoxLayout()
        self.verticalLayout_97.setObjectName("verticalLayout_97")
        self.label_103 = QtWidgets.QLabel(self.layoutWidget)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.verticalLayout_97.addWidget(self.label_103)
        self.check_32_25 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_25.setText("")
        self.check_32_25.setObjectName("check_32_25")
        self.verticalLayout_97.addWidget(self.check_32_25)
        self.horizontalLayout_5.addLayout(self.verticalLayout_97)
        self.verticalLayout_98 = QtWidgets.QVBoxLayout()
        self.verticalLayout_98.setObjectName("verticalLayout_98")
        self.label_104 = QtWidgets.QLabel(self.layoutWidget)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.verticalLayout_98.addWidget(self.label_104)
        self.check_32_24 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_24.setText("")
        self.check_32_24.setObjectName("check_32_24")
        self.verticalLayout_98.addWidget(self.check_32_24)
        self.horizontalLayout_5.addLayout(self.verticalLayout_98)
        self.verticalLayout_99 = QtWidgets.QVBoxLayout()
        self.verticalLayout_99.setObjectName("verticalLayout_99")
        self.label_105 = QtWidgets.QLabel(self.layoutWidget)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName("label_105")
        self.verticalLayout_99.addWidget(self.label_105)
        self.check_32_23 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_23.setText("")
        self.check_32_23.setObjectName("check_32_23")
        self.verticalLayout_99.addWidget(self.check_32_23)
        self.horizontalLayout_5.addLayout(self.verticalLayout_99)
        self.verticalLayout_100 = QtWidgets.QVBoxLayout()
        self.verticalLayout_100.setObjectName("verticalLayout_100")
        self.label_106 = QtWidgets.QLabel(self.layoutWidget)
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setObjectName("label_106")
        self.verticalLayout_100.addWidget(self.label_106)
        self.check_32_22 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_22.setText("")
        self.check_32_22.setObjectName("check_32_22")
        self.verticalLayout_100.addWidget(self.check_32_22)
        self.horizontalLayout_5.addLayout(self.verticalLayout_100)
        self.verticalLayout_101 = QtWidgets.QVBoxLayout()
        self.verticalLayout_101.setObjectName("verticalLayout_101")
        self.label_107 = QtWidgets.QLabel(self.layoutWidget)
        self.label_107.setAlignment(QtCore.Qt.AlignCenter)
        self.label_107.setObjectName("label_107")
        self.verticalLayout_101.addWidget(self.label_107)
        self.check_32_21 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_21.setText("")
        self.check_32_21.setObjectName("check_32_21")
        self.verticalLayout_101.addWidget(self.check_32_21)
        self.horizontalLayout_5.addLayout(self.verticalLayout_101)
        self.verticalLayout_102 = QtWidgets.QVBoxLayout()
        self.verticalLayout_102.setObjectName("verticalLayout_102")
        self.label_108 = QtWidgets.QLabel(self.layoutWidget)
        self.label_108.setAlignment(QtCore.Qt.AlignCenter)
        self.label_108.setObjectName("label_108")
        self.verticalLayout_102.addWidget(self.label_108)
        self.check_32_20 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_20.setText("")
        self.check_32_20.setObjectName("check_32_20")
        self.verticalLayout_102.addWidget(self.check_32_20)
        self.horizontalLayout_5.addLayout(self.verticalLayout_102)
        self.verticalLayout_103 = QtWidgets.QVBoxLayout()
        self.verticalLayout_103.setObjectName("verticalLayout_103")
        self.label_109 = QtWidgets.QLabel(self.layoutWidget)
        self.label_109.setAlignment(QtCore.Qt.AlignCenter)
        self.label_109.setObjectName("label_109")
        self.verticalLayout_103.addWidget(self.label_109)
        self.check_32_19 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_19.setText("")
        self.check_32_19.setObjectName("check_32_19")
        self.verticalLayout_103.addWidget(self.check_32_19)
        self.horizontalLayout_5.addLayout(self.verticalLayout_103)
        self.verticalLayout_104 = QtWidgets.QVBoxLayout()
        self.verticalLayout_104.setObjectName("verticalLayout_104")
        self.label_110 = QtWidgets.QLabel(self.layoutWidget)
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setObjectName("label_110")
        self.verticalLayout_104.addWidget(self.label_110)
        self.check_32_18 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_18.setText("")
        self.check_32_18.setObjectName("check_32_18")
        self.verticalLayout_104.addWidget(self.check_32_18)
        self.horizontalLayout_5.addLayout(self.verticalLayout_104)
        self.verticalLayout_105 = QtWidgets.QVBoxLayout()
        self.verticalLayout_105.setObjectName("verticalLayout_105")
        self.label_111 = QtWidgets.QLabel(self.layoutWidget)
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_105.addWidget(self.label_111)
        self.check_32_17 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_17.setText("")
        self.check_32_17.setObjectName("check_32_17")
        self.verticalLayout_105.addWidget(self.check_32_17)
        self.horizontalLayout_5.addLayout(self.verticalLayout_105)
        self.verticalLayout_106 = QtWidgets.QVBoxLayout()
        self.verticalLayout_106.setObjectName("verticalLayout_106")
        self.label_112 = QtWidgets.QLabel(self.layoutWidget)
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.verticalLayout_106.addWidget(self.label_112)
        self.check_32_16 = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_32_16.setText("")
        self.check_32_16.setObjectName("check_32_16")
        self.verticalLayout_106.addWidget(self.check_32_16)
        self.horizontalLayout_5.addLayout(self.verticalLayout_106)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.hex_table = QtWidgets.QTableWidget(self.hex_tab)
        self.hex_table.setGeometry(QtCore.QRect(10, 250, 711, 381))
        self.hex_table.setRowCount(32)
        self.hex_table.setColumnCount(4)
        self.hex_table.setObjectName("hex_table")
        self.hex_bit_edit_check = QtWidgets.QCheckBox(self.hex_tab)
        self.hex_bit_edit_check.setGeometry(QtCore.QRect(480, 150, 71, 20))
        self.hex_bit_edit_check.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hex_bit_edit_check.setObjectName("hex_bit_edit_check")
        self.layoutWidget1 = QtWidgets.QWidget(self.hex_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(480, 190, 195, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.hex_bit_clear_all_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.hex_bit_clear_all_btn.setObjectName("hex_bit_clear_all_btn")
        self.horizontalLayout_7.addWidget(self.hex_bit_clear_all_btn)
        self.hex_bit_set_all_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.hex_bit_set_all_btn.setObjectName("hex_bit_set_all_btn")
        self.horizontalLayout_7.addWidget(self.hex_bit_set_all_btn)
        self.line_4 = QtWidgets.QFrame(self.hex_tab)
        self.line_4.setGeometry(QtCore.QRect(0, 50, 721, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.widget = QtWidgets.QWidget(self.hex_tab)
        self.widget.setGeometry(QtCore.QRect(10, 10, 681, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.hex_line_edit_addr = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hex_line_edit_addr.sizePolicy().hasHeightForWidth())
        self.hex_line_edit_addr.setSizePolicy(sizePolicy)
        self.hex_line_edit_addr.setMinimumSize(QtCore.QSize(0, 0))
        self.hex_line_edit_addr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hex_line_edit_addr.setObjectName("hex_line_edit_addr")
        self.horizontalLayout_6.addWidget(self.hex_line_edit_addr)
        self.hex_addr_up = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.hex_addr_up.setFont(font)
        self.hex_addr_up.setFlat(False)
        self.hex_addr_up.setObjectName("hex_addr_up")
        self.horizontalLayout_6.addWidget(self.hex_addr_up)
        self.hex_addr_down = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.hex_addr_down.setFont(font)
        self.hex_addr_down.setObjectName("hex_addr_down")
        self.horizontalLayout_6.addWidget(self.hex_addr_down)
        self.hex_addr_cfg_tip = QtWidgets.QLabel(self.widget)
        self.hex_addr_cfg_tip.setObjectName("hex_addr_cfg_tip")
        self.horizontalLayout_6.addWidget(self.hex_addr_cfg_tip)
        self.horizontalLayout_6.setStretch(1, 3)
        self.horizontalLayout_6.setStretch(2, 3)
        self.horizontalLayout_6.setStretch(3, 3)
        self.horizontalLayout_6.setStretch(4, 4)
        self.widget1 = QtWidgets.QWidget(self.hex_tab)
        self.widget1.setGeometry(QtCore.QRect(11, 70, 561, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hex_update_value_enable_radio = QtWidgets.QRadioButton(self.widget1)
        self.hex_update_value_enable_radio.setObjectName("hex_update_value_enable_radio")
        self.horizontalLayout.addWidget(self.hex_update_value_enable_radio)
        self.hex_line_edit_value = QtWidgets.QLineEdit(self.widget1)
        self.hex_line_edit_value.setObjectName("hex_line_edit_value")
        self.horizontalLayout.addWidget(self.hex_line_edit_value)
        self.hex_update_reset_enable_radio = QtWidgets.QRadioButton(self.widget1)
        self.hex_update_reset_enable_radio.setObjectName("hex_update_reset_enable_radio")
        self.horizontalLayout.addWidget(self.hex_update_reset_enable_radio)
        self.hex_line_edit_reset_value = QtWidgets.QLineEdit(self.widget1)
        self.hex_line_edit_reset_value.setObjectName("hex_line_edit_reset_value")
        self.horizontalLayout.addWidget(self.hex_line_edit_reset_value)
        self.hex_save_btn = QtWidgets.QPushButton(self.widget1)
        self.hex_save_btn.setObjectName("hex_save_btn")
        self.horizontalLayout.addWidget(self.hex_save_btn)
        self.hex_reload_btn = QtWidgets.QPushButton(self.widget1)
        self.hex_reload_btn.setObjectName("hex_reload_btn")
        self.horizontalLayout.addWidget(self.hex_reload_btn)
        self.widget2 = QtWidgets.QWidget(self.hex_tab)
        self.widget2.setGeometry(QtCore.QRect(330, 640, 371, 30))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.hex_table_func_list_label = QtWidgets.QLabel(self.widget2)
        self.hex_table_func_list_label.setObjectName("hex_table_func_list_label")
        self.horizontalLayout_8.addWidget(self.hex_table_func_list_label)
        self.hex_table_edit_check = QtWidgets.QCheckBox(self.widget2)
        self.hex_table_edit_check.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hex_table_edit_check.setObjectName("hex_table_edit_check")
        self.horizontalLayout_8.addWidget(self.hex_table_edit_check)
        self.hex_table_update_btn = QtWidgets.QPushButton(self.widget2)
        self.hex_table_update_btn.setObjectName("hex_table_update_btn")
        self.horizontalLayout_8.addWidget(self.hex_table_update_btn)
        self.tabWidget.addTab(self.hex_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cfg_text_edit = QtWidgets.QTextEdit(self.tab_2)
        self.cfg_text_edit.setGeometry(QtCore.QRect(10, 90, 701, 581))
        self.cfg_text_edit.setObjectName("cfg_text_edit")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 11, 612, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cfg_line_edit_addr = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cfg_line_edit_addr.setObjectName("cfg_line_edit_addr")
        self.horizontalLayout_2.addWidget(self.cfg_line_edit_addr)
        self.cfg_read_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.cfg_read_btn.setObjectName("cfg_read_btn")
        self.horizontalLayout_2.addWidget(self.cfg_read_btn)
        self.cfg_demo_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.cfg_demo_btn.setObjectName("cfg_demo_btn")
        self.horizontalLayout_2.addWidget(self.cfg_demo_btn)
        self.cfg_clear_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.cfg_clear_btn.setObjectName("cfg_clear_btn")
        self.horizontalLayout_2.addWidget(self.cfg_clear_btn)
        self.cfg_add_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.cfg_add_btn.setObjectName("cfg_add_btn")
        self.horizontalLayout_2.addWidget(self.cfg_add_btn)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 46, 611, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cfg_up_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.cfg_up_btn.setObjectName("cfg_up_btn")
        self.horizontalLayout_3.addWidget(self.cfg_up_btn)
        self.cfg_down_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.cfg_down_btn.setObjectName("cfg_down_btn")
        self.horizontalLayout_3.addWidget(self.cfg_down_btn)
        self.cfg_read_json_cfg_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.cfg_read_json_cfg_btn.setObjectName("cfg_read_json_cfg_btn")
        self.horizontalLayout_3.addWidget(self.cfg_read_json_cfg_btn)
        self.cfg_read_json_value_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.cfg_read_json_value_btn.setObjectName("cfg_read_json_value_btn")
        self.horizontalLayout_3.addWidget(self.cfg_read_json_value_btn)
        self.cfg_generate_reg_c_file = QtWidgets.QPushButton(self.layoutWidget3)
        self.cfg_generate_reg_c_file.setObjectName("cfg_generate_reg_c_file")
        self.horizontalLayout_3.addWidget(self.cfg_generate_reg_c_file)
        self.cfg_addr_list_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.cfg_addr_list_btn.setObjectName("cfg_addr_list_btn")
        self.horizontalLayout_3.addWidget(self.cfg_addr_list_btn)
        self.tabWidget.addTab(self.tab_2, "")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1058, 141, 16, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_81.setText(_translate("MainWindow", "15"))
        self.label_82.setText(_translate("MainWindow", "14"))
        self.label_83.setText(_translate("MainWindow", "13"))
        self.label_84.setText(_translate("MainWindow", "12"))
        self.label_85.setText(_translate("MainWindow", "11"))
        self.label_86.setText(_translate("MainWindow", "10"))
        self.label_87.setText(_translate("MainWindow", "9"))
        self.label_88.setText(_translate("MainWindow", "8"))
        self.label_89.setText(_translate("MainWindow", "7"))
        self.label_90.setText(_translate("MainWindow", "6"))
        self.label_91.setText(_translate("MainWindow", "5"))
        self.label_92.setText(_translate("MainWindow", "4"))
        self.label_93.setText(_translate("MainWindow", "3"))
        self.label_94.setText(_translate("MainWindow", "2"))
        self.label_95.setText(_translate("MainWindow", "1"))
        self.label_96.setText(_translate("MainWindow", "0"))
        self.label_97.setText(_translate("MainWindow", "31"))
        self.label_98.setText(_translate("MainWindow", "30"))
        self.label_99.setText(_translate("MainWindow", "29"))
        self.label_100.setText(_translate("MainWindow", "28"))
        self.label_101.setText(_translate("MainWindow", "27"))
        self.label_102.setText(_translate("MainWindow", "26"))
        self.label_103.setText(_translate("MainWindow", "25"))
        self.label_104.setText(_translate("MainWindow", "24"))
        self.label_105.setText(_translate("MainWindow", "23"))
        self.label_106.setText(_translate("MainWindow", "22"))
        self.label_107.setText(_translate("MainWindow", "21"))
        self.label_108.setText(_translate("MainWindow", "20"))
        self.label_109.setText(_translate("MainWindow", "19"))
        self.label_110.setText(_translate("MainWindow", "18"))
        self.label_111.setText(_translate("MainWindow", "17"))
        self.label_112.setText(_translate("MainWindow", "16"))
        self.hex_bit_edit_check.setText(_translate("MainWindow", "Enable"))
        self.hex_bit_clear_all_btn.setToolTip(_translate("MainWindow", "set all bit to 0"))
        self.hex_bit_clear_all_btn.setText(_translate("MainWindow", "ClearAll"))
        self.hex_bit_set_all_btn.setToolTip(_translate("MainWindow", "set all bit to 1"))
        self.hex_bit_set_all_btn.setText(_translate("MainWindow", "SetAll"))
        self.label.setText(_translate("MainWindow", "Addr "))
        self.hex_line_edit_addr.setText(_translate("MainWindow", "0x00000000"))
        self.hex_addr_up.setToolTip(_translate("MainWindow", "up addr"))
        self.hex_addr_up.setText(_translate("MainWindow", "Up"))
        self.hex_addr_down.setToolTip(_translate("MainWindow", "down addr"))
        self.hex_addr_down.setText(_translate("MainWindow", "Down"))
        self.hex_addr_cfg_tip.setText(_translate("MainWindow", "Not find config"))
        self.hex_update_value_enable_radio.setToolTip(_translate("MainWindow", "update bit cfg value to Reset"))
        self.hex_update_value_enable_radio.setText(_translate("MainWindow", "Value"))
        self.hex_line_edit_value.setText(_translate("MainWindow", "0x00000000"))
        self.hex_update_reset_enable_radio.setToolTip(_translate("MainWindow", "update bit cfg value to Value"))
        self.hex_update_reset_enable_radio.setText(_translate("MainWindow", "Reset"))
        self.hex_line_edit_reset_value.setText(_translate("MainWindow", "0x00000000"))
        self.hex_save_btn.setToolTip(_translate("MainWindow", "save value to json file"))
        self.hex_save_btn.setText(_translate("MainWindow", "Save"))
        self.hex_reload_btn.setToolTip(_translate("MainWindow", "reload all data from json"))
        self.hex_reload_btn.setText(_translate("MainWindow", "Reload"))
        self.hex_table_func_list_label.setText(_translate("MainWindow", "Not func list config"))
        self.hex_table_edit_check.setText(_translate("MainWindow", "Enable"))
        self.hex_table_update_btn.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hex_tab), _translate("MainWindow", "HEX"))
        self.label_3.setText(_translate("MainWindow", "Addr"))
        self.cfg_read_btn.setToolTip(_translate("MainWindow", "read addr config"))
        self.cfg_read_btn.setText(_translate("MainWindow", "Read"))
        self.cfg_demo_btn.setToolTip(_translate("MainWindow", "read json cfg file demo"))
        self.cfg_demo_btn.setText(_translate("MainWindow", "Demo"))
        self.cfg_clear_btn.setToolTip(_translate("MainWindow", "clear text config"))
        self.cfg_clear_btn.setText(_translate("MainWindow", "Clear"))
        self.cfg_add_btn.setToolTip(_translate("MainWindow", "save addr cfg to json"))
        self.cfg_add_btn.setText(_translate("MainWindow", "AddCfg"))
        self.cfg_up_btn.setToolTip(_translate("MainWindow", "addr minus 4"))
        self.cfg_up_btn.setText(_translate("MainWindow", "Up"))
        self.cfg_down_btn.setToolTip(_translate("MainWindow", "addr plus 4"))
        self.cfg_down_btn.setText(_translate("MainWindow", "Down"))
        self.cfg_read_json_cfg_btn.setToolTip(_translate("MainWindow", "read all json cfg file"))
        self.cfg_read_json_cfg_btn.setText(_translate("MainWindow", "ReadAllCfg"))
        self.cfg_read_json_value_btn.setToolTip(_translate("MainWindow", "read all value file"))
        self.cfg_read_json_value_btn.setText(_translate("MainWindow", "ReadAllValue"))
        self.cfg_generate_reg_c_file.setToolTip(_translate("MainWindow", "generate register c file"))
        self.cfg_generate_reg_c_file.setText(_translate("MainWindow", "GenClang"))
        self.cfg_addr_list_btn.setToolTip(_translate("MainWindow", "get all config addr list"))
        self.cfg_addr_list_btn.setText(_translate("MainWindow", "AddrList"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CFG"))

